import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header style={{ padding: '1rem', borderBottom: '1px solid #ccc' }}>
          <nav style={{ display: 'flex', gap: '1rem' }}>
            <a href="/">Inicio</a>
            <a href="/about">Acerca de</a>
            <a href="/contact">Contacto</a>
          </nav>
        </header>

        <main style={{ minHeight: '80vh', padding: '2rem' }}>
          {children}
        </main>

        <footer style={{ padding: '1rem', borderTop: '1px solid #ccc', textAlign: 'center' }}>
          <small>© 2025 Mi Sitio</small>
        </footer>
      </body>
    </html>
  );
}
